### ISSUE TITLE
Use state machine for tracking Manager, Worker, and Node state progression

### ISSUE THREAD

**Issue by edavalosanaya** [ChimeraPy/ChimeraPyOrchestrator#24]
Having various attributes, like ``collecting`` and ``running`` for ``Manager`` and ``Node`` might cause problems and become unstable to monitor invalid request or actions. The use of a state machine could help avoid issues like this and clearly define the lifecycle of ChimeraPy components.

**Comment by umesh-timalsina** [comment]
Closed #115/#116
